<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/CSS/Admin/About Us.css">
    <title>About Us</title>
</head>

<body>
    <div class="wrapper">
        <div class="background-color">
            <div class="bg-1"></div>
            <div class="bg-2"></div>
        </div>
        <div class="about-container">
            <div class="image-container">
                <img src="/Images/Admin/About bg.svg" alt="">
            </div>
            <div class="text-container">
                <h1>About Us</h1>
                <h3>Namste...!</h3><br>
                <p>"We assist in sustaining rural development through technology"<br>
                    The Gram Panchayt Website is specially developed for Gram Panchayat to support Digital India.
                    It helps you to run all Gram Panchayath's Operations smoothly and makes the process very easy.
                    All data is safe and secured in the website, and helps you to operate any where as it supports
                    web-based and mobile applications. All important documents snd processes are hassle free such
                    as birth, marriage, death certificates and other schemes which can be issued & generated by
                    Gram Panchyat as per government format.</p>
            </div>
        </div>
    </div>
</body>

</html>